/**
 * Environment probe tests.
 *
 * The probe is the dependency that makes PBR materials visible at all, so the
 * tests here are less about the texture and more about the *contract*: it must
 * exist, it must be linear, it must carry structure rather than being a flat
 * wash, and it must never disturb the world's deterministic PRNG stream.
 *
 * Everything is testable without a GPU because the pixels are generated by hand
 * as a Float32Array - which is the reason the probe is built this way instead of
 * with `PMREMGenerator`.
 */
import { test } from 'node:test';
import assert from 'node:assert/strict';
import * as THREE from 'three';
import {
  ENV, buildProbePixels, buildEnvProbe, applyEnvProbe, disposeEnvProbe,
} from '../src/sim/environment.js';

/** Sample a pixel from the returned array, clamped to the image. */
function pixel(data, x, y) {
  const w = ENV.width;
  const h = ENV.width / 2;
  const cx = Math.max(0, Math.min(w - 1, x));
  const cy = Math.max(0, Math.min(h - 1, y));
  const i = (cy * w + cx) * 4;
  return [data[i], data[i + 1], data[i + 2], data[i + 3]];
}

/** Mean luminance of a horizontal strip of rows. */
function stripLuminance(data, y0, y1) {
  const w = ENV.width;
  let sum = 0;
  let n = 0;
  for (let y = y0; y < y1; y += 1) {
    for (let x = 0; x < w; x += 1) {
      const i = (y * w + x) * 4;
      sum += data[i] * 0.3 + data[i + 1] * 0.6 + data[i + 2] * 0.1;
      n += 1;
    }
  }
  return sum / n;
}

test('the probe has the dimensions an equirect texture requires', () => {
  const data = buildProbePixels(1);
  // Half the width: an equirect that is square is wrong and three will sample it
  // distorted. This is the single easiest thing to get wrong, so it is pinned.
  assert.strictEqual(data.length, ENV.width * (ENV.width / 2) * 4,
    'the probe is not width x height/2 x RGBA');
  assert.strictEqual(ENV.width % 2, 0, 'width must be even to halve cleanly');
});

test('every pixel is a finite, non-negative, opaque value', () => {
  const data = buildProbePixels(1);
  for (let i = 0; i < data.length; i += 4) {
    for (let c = 0; c < 3; c += 1) {
      const v = data[i + c];
      assert.ok(Number.isFinite(v), 'non-finite radiance at channel ' + c);
      // A negative radiance is meaningless and would make a reflection subtract
      // light rather than add it.
      assert.ok(v >= 0, 'negative radiance ' + v + ' at channel ' + c);
    }
    assert.strictEqual(data[i + 3], 1, 'the probe must be opaque');
  }
});

test('the probe is a gradient field, not a flat wash', () => {
  const data = buildProbePixels(1);
  // If the vertical gradient were missing the probe would supply uniform
  // indirect light, and every material would look exactly as flat as it did
  // under Lambert - which is the failure this whole module exists to fix.
  const south = stripLuminance(data, 0, 4);
  const north = stripLuminance(data, ENV.width / 2 - 4, ENV.width / 2);
  assert.ok(Math.abs(north - south) > 0.01,
    'the zenith and nadir carry the same light (' + north.toFixed(4) + ' vs ' +
    south.toFixed(4) + '): the gradient is gone');
});

test('the sky and the probe agree on where the galactic band runs', () => {
  // The band is the most recognisable feature of a reflection, so if the probe
  // derived its own plane the bright smear would appear where the real band is
  // not. This walks the probe's band plane and checks it is brighter than the
  // average, using the same tilt `sky.js` uses.
  const data = buildProbePixels(1);
  const w = ENV.width;
  const h = ENV.width / 2;
  const normal = new THREE.Vector3(
    Math.sin(0.42), Math.cos(0.42), 0,
  ).normalize();

  let inBand = 0;
  let inBandN = 0;
  let all = 0;
  let allN = 0;
  for (let y = 0; y < h; y += 1) {
    const v = (y + 0.5) / h;
    const theta = v * Math.PI;
    for (let x = 0; x < w; x += 1) {
      const phi = ((x + 0.5) / w) * Math.PI * 2;
      const dir = new THREE.Vector3(
        -Math.cos(phi) * Math.sin(theta),
        Math.cos(theta),
        Math.sin(phi) * Math.sin(theta),
      );
      const i = (y * w + x) * 4;
      const lum = data[i] * 0.3 + data[i + 1] * 0.6 + data[i + 2] * 0.1;
      all += lum; allN += 1;
      if (Math.abs(dir.dot(normal)) < 0.16) { inBand += lum; inBandN += 1; }
    }
  }
  assert.ok(inBandN > 0, 'no pixels fell inside the band');
  const bandMean = inBand / inBandN;
  const allMean = all / allN;
  assert.ok(bandMean > allMean * 1.15,
    'the band is not brighter than the sky (' + bandMean.toFixed(4) + ' vs ' +
    allMean.toFixed(4) + '): the probe and sky.js disagree about the plane');
});

test('the probe is bright enough to lift a dark hull but not to blow it out', () => {
  const data = buildProbePixels(1);
  let max = 0;
  let sum = 0;
  let n = 0;
  for (let i = 0; i < data.length; i += 4) {
    const lum = data[i] * 0.3 + data[i + 1] * 0.6 + data[i + 2] * 0.1;
    max = Math.max(max, lum);
    sum += lum; n += 1;
  }
  const mean = sum / n;
  // The star glint is the intended peak. If the max were ~mean, there would be
  // nothing for a polished surface to catch.
  assert.ok(max > mean * 4, 'the probe has no bright feature to reflect');
  // But the *mean* must stay modest: this is indirect light and must not compete
  // with the directional star light that shapes the facets.
  assert.ok(mean < 0.35,
    'the probe is too bright on average (' + mean.toFixed(3) +
    '): it will wash out the honest shading');
});

test('the probe is deterministic from its seed and varies with it', () => {
  const a = buildProbePixels(7);
  const b = buildProbePixels(7);
  const c = buildProbePixels(8);
  assert.deepStrictEqual(Array.from(a), Array.from(b),
    'the same seed produced a different probe');
  assert.notDeepStrictEqual(Array.from(a), Array.from(c),
    'a different seed produced an identical probe');
});

test('building a probe does not disturb the world PRNG stream', () => {
  // The probe uses its own fixed stream. If it borrowed the shared one, booting
  // the renderer could shift every system's generated contents - a bug that
  // would look like "the galaxy changed" for no visible reason.
  const data = buildProbePixels(undefined);
  const again = buildProbePixels(undefined);
  assert.deepStrictEqual(Array.from(data), Array.from(again));
});

test('the texture is linear-space with the equirect mapping PBR needs', () => {
  const tex = buildEnvProbe(1);
  assert.strictEqual(tex.mapping, THREE.EquirectangularReflectionMapping,
    'without the equirect mapping three will not cube-sample the probe');
  // Linear, not sRGB: three would decode an sRGB-tagged texture and roughly
  // square the values, making every reflection far darker than authored.
  assert.strictEqual(tex.colorSpace, THREE.LinearSRGBColorSpace,
    'the probe must not be treated as sRGB or it will render too dark');
  assert.strictEqual(tex.type, THREE.FloatType,
    'a half-float or byte texture cannot carry radiance above 1.0');
  // Longitude wraps, latitude clamps: wrapping over the poles is wrong.
  assert.strictEqual(tex.wrapS, THREE.RepeatWrapping);
  assert.strictEqual(tex.wrapT, THREE.ClampToEdgeWrapping);
  assert.strictEqual(tex.generateMipmaps, false);
  tex.dispose();
});

test('the probe attaches to a scene as its environment', () => {
  const scene = new THREE.Scene();
  const tex = buildEnvProbe(1);
  const previous = applyEnvProbe(scene, tex);
  assert.strictEqual(previous, null, 'a fresh scene had an environment');
  assert.strictEqual(scene.environment, tex,
    'the materials will render black without this');
  const replaced = applyEnvProbe(scene, null);
  assert.strictEqual(replaced, tex, 'the previous probe was not returned');
  assert.strictEqual(scene.environment, null);
  tex.dispose();
});

test('disposing a probe tolerates null and is safe to call twice', () => {
  assert.doesNotThrow(() => disposeEnvProbe(null));
  assert.doesNotThrow(() => disposeEnvProbe(undefined));
  const tex = buildEnvProbe(1);
  disposeEnvProbe(tex);
  assert.doesNotThrow(() => disposeEnvProbe(tex));
});

test('the module exposes a default mirror for the browser facade', async () => {
  // `main.js` reaches these through the default-export mirror in the other sim
  // modules, so the shape has to match as well as the named exports.
  const mod = await import('../src/sim/environment.js');
  assert.strictEqual(mod.default.ENV, ENV);
  assert.strictEqual(mod.default.buildEnvProbe, buildEnvProbe);
  assert.strictEqual(mod.default.applyEnvProbe, applyEnvProbe);
  assert.strictEqual(mod.default.disposeEnvProbe, disposeEnvProbe);
});
